GET http://localhost:3003/api/blogs HTTP/1.1

###
POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "Ma test",
    "author": "Football",
    "url": "http://www.google.com",
    "likes": 0,
    "userId": "60d79921c46324d7d6c8ff8f"
}

###
DELETE http://localhost:3003/api/blogs/:id HTTP/1.1

###
PUT http://localhost:3003/api/blogs/:id HTTP/1.1
content-type: application/json

{
    "title": "The magic book in the magic castle",
    "author": "Trendy Heels"
}

###
GET http://localhost:3003/api/users HTTP/1.1

###
POST http://localhost:3003/api/users HTTP/1.1
content-type: application/json

{
    "name": "Rad Head",
    "username": "Rad Shack",
    "password": "shack",
    "blogId": "60dd6f132b472092efbfece0"
}

###
POST http://localhost:3003/api/login HTTP/1.1
content-type: application/json

{
    "username": "Rad Shack",
    "password": "shack"
}