GET http://localhost:3003/api/blogs HTTP/1.1

###
POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlJhZCBTaGFjayIsImlkIjoiNjBkZDZmNmFkMTk2MTk5MzYzMDk3MGZhIiwiaWF0IjoxNjI1MTc0MDM0fQ.WvUIcasf3rR5P_eyTsu1lm-KV-r9qn9CC5XyBgSrDmU

{
    "title": "Token6 test",
    "author": "Not a Football at all",
    "url": "https://www.google.com",
    "likes": 4,
    "userId": "60dd6f6ad1961993630970fa"
}

###
DELETE http://localhost:3003/api/blogs/:id HTTP/1.1
Authorization: 

###
PUT http://localhost:3003/api/blogs/:id HTTP/1.1
content-type: application/json

{
    "title": "The magic book in the magic castle",
    "author": "Trendy Heels"
}

###
GET http://localhost:3003/api/users HTTP/1.1

###
POST http://localhost:3003/api/users HTTP/1.1
content-type: application/json

{
    "name": "Rad Head",
    "username": "Rad Shack",
    "password": "shack",
    "blogId": "60dd6f132b472092efbfece0"
}

###
POST http://localhost:3003/api/login HTTP/1.1
content-type: application/json

{
    "username": "Sheldor",
    "password": "sheldon"
}