GET http://localhost:3003/api/blogs HTTP/1.1

###
POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json
Authorization: bearer token

{
    "title": "Token7 test",
    "author": "Not a Football at all here",
    "url": "https://www.google.com",
    "likes": 8,
    "userId": "60e4d3e7021f836394921fbb"
}

###
DELETE http://localhost:3003/api/blogs/:id HTTP/1.1
Authorization: 

###
PUT http://localhost:3003/api/blogs/:id HTTP/1.1
content-type: application/json

{
    "title": "The magic book in the magic castle",
    "author": "Trendy Heels"
}

###
GET http://localhost:3003/api/users HTTP/1.1

###
GET http://localhost:3003/api/users/********* HTTP/1.1

###
POST http://localhost:3003/api/users HTTP/1.1
content-type: application/json

{
    "name": "Blow Fish",
    "username": "fish",
    "password": "123456"
}

###
POST http://localhost:3003/api/login HTTP/1.1
content-type: application/json

{
    "username": "fish",
    "password": "123456"
}